### ISSUE TITLE
This is not an issue but a question as I don't know how to do that. Happy to remove it if that is a problem.

### ISSUE THREAD

**Issue by cknyakina** [taylor85345/neon-hyprland-theme#1]
I have Hyprland and I am amazed by your animated wallpapers. How did you set that up?

**Comment by taylor85345** [comment]
The wallpaper utility is mpvpaper, which just sets an mpv instance as the wallpaper playing a video on a continuous loop. The actual video clips are screen captures from the game Stray, which I edited in Kdenlive to loop seamlessly.

Hope that helps :)

**Comment by cknyakina** [comment]
Thanks for that. Appreciate it.
